extends: stylelint-config-sass-guidelines
rules:
  block-no-empty:
    - true
    - severity: warning
  indentation:
    - 2
    - severity: warning
  max-nesting-depth: null
  selector-no-qualifying-type:
    - true
    - severity: warning