version: '3'
services:
  client:
    container_name: tagcon_client_prod
    build: ./client
    ports:
      - 80:80
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - tagcon_network

  api:
    container_name: tagcon_api_prod
    build: ./api
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      - tagcon_network

  db:
    container_name: tagcon_db_prod
    image: mongo
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - tagcon_network

networks:
  tagcon_network:
      driver: bridge
