env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-restricted-globals: warn
  arrow-parens: off
  no-console: off
  comma-style:
    - error
    - first
  one-var:
    - error
    - consecutive
  no-param-reassign: warn
  comma-dangle:
    - error
    - never
  indent: 
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        var: 1
        let: 1
        const: 2
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/prefer-default-export:
    - warn