database:
  name: tagcon_dev
  url: mongodb://db:27017

test:
  database:
    name: tagcon_test
    url: mongodb://db:27017

production:
    database:
      name: tagcon
      url: mongodb://db:27017