version: '3'
services:
  api:
      build: 
        context: .
        dockerfile: Dockerfile.test
      command: yarn test --watchAll --runInBand
      volumes:
        - .:/api
      ports:
        - 3000:3000